/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarListings.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'CarListings.view.ListaCarros',
        'Ext.panel.Panel'
    ],

    layout: {
        type: 'border',
        regionWeights: {
            north: 30,
            south: 30,
            center: 0,
            west: 30,
            east: 30
        }
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'listacarros',
                    region: 'center'
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    id: 'PanelRegionEste',
                    width: 50
                },
                {
                    xtype: 'panel',
                    region: 'east',
                    id: 'PanelRegionOeste',
                    width: 50
                },
                {
                    xtype: 'panel',
                    region: 'north',
                    height: 50,
                    id: 'PanelRegionNorte'
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 50,
                    id: 'PanelRegionSur'
                }
            ]
        });

        me.callParent(arguments);
    }

});